apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attus.fullname" . }}-api
  labels: {{ include "attus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "attus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "attus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-api"
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.postgres.fullnameOverride | default "postgres" }}:5432/{{ .Values.postgres.auth.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.auth.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: attus-processo-db
                  key: db-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.app.kafka.bootstrapServers }}