apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attus.fullname" . }}-publisher
  labels: {{ include "attus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "attus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "attus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: publisher
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-processos-evento-kafka"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.app.kafka.bootstrapServers }}