apiVersion: v2
name: attus-processo-msa
type: application
version: 0.1.0
appVersion: "1.0.0-SNAPSHOT"

dependencies:
  - name: postgresql
    version: 13.2.21
    repository: https://charts.bitnami.com/bitnami
    alias: postgres

  - name: kafka
    version: 26.6.2
    repository: https://charts.bitnami.com/bitnami
